In [1]:
import numpy as np


In [4]:
zero = np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [5]:
one=np.ones(5)
one

array([1., 1., 1., 1., 1.])

In [9]:
num = np.arange(1,11)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
ev = np.arange(2,21,2)
ev

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
a = np.random.rand(10)
a

array([0.5206362 , 0.26623   , 0.22237101, 0.95433559, 0.99618768,
       0.08941582, 0.467356  , 0.98048099, 0.50674956, 0.2669723 ])

In [33]:
#Task 1
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [25]:
print("ndim : ",arr.ndim)

ndim :  1


In [26]:
arr.shape

(100,)

In [27]:
arr.size

100

In [29]:
arr.dtype

dtype('int64')

In [30]:
arr.itemsize

8

In [31]:
arr.nbytes

800

In [41]:
#Task2
k = np.array([10.55,1.21,4.5,12.56,9.011])
k

array([10.55 ,  1.21 ,  4.5  , 12.56 ,  9.011])

In [42]:
k.astype(np.float32)

array([10.55 ,  1.21 ,  4.5  , 12.56 ,  9.011], dtype=float32)

In [43]:
k.astype(np.float64)

array([10.55 ,  1.21 ,  4.5  , 12.56 ,  9.011])

In [44]:
k.astype(np.int32)

array([10,  1,  4, 12,  9], dtype=int32)

In [96]:
#Task 3
data = np.random.rand(8,5)
data

array([[0.62813264, 0.96183561, 0.97460513, 0.19245092, 0.49252646],
       [0.95618969, 0.08844283, 0.93157777, 0.13324016, 0.54991894],
       [0.17417524, 0.70842247, 0.99712238, 0.6618676 , 0.93126672],
       [0.68055551, 0.8413508 , 0.57544884, 0.00111559, 0.0903709 ],
       [0.71343483, 0.31988311, 0.78958621, 0.99183742, 0.80059169],
       [0.73326581, 0.12009904, 0.81327287, 0.74385754, 0.03325106],
       [0.61145105, 0.53406407, 0.71094514, 0.60476926, 0.88429578],
       [0.05814679, 0.84729418, 0.164699  , 0.77063386, 0.77839852]])

In [97]:
data.shape

(8, 5)

In [98]:
data.dtype

dtype('float64')

In [99]:
data.size

40

In [100]:
data.ndim

2

In [101]:
#Task 4
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [102]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [103]:
#Task 5
matrix = np.arange(1,37)
matrix


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [104]:
a = matrix.reshape(6,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [105]:
np.diag(a)

array([ 1,  8, 15, 22, 29, 36])

In [106]:
b= np.fliplr(a)
np.diag(b)

array([ 6, 11, 16, 21, 26, 31])

In [107]:
m = a[2:4,2:4]
m

array([[15, 16],
       [21, 22]])

In [108]:
k= a[0::2,:]
k

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30]])

In [113]:
#Task 6
d = np.arange(1,49).reshape(2,4,6)
d

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48]]])

In [118]:
d[:,:,0]

array([[ 1,  7, 13, 19],
       [25, 31, 37, 43]])

In [122]:
d[0,::,::]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [124]:
d[1,1:3:,:]

array([[31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42]])

In [127]:
#Task 7
Arr = np.arange(1,13).reshape(4,3)
Arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [130]:
Arr.shape

(4, 3)

In [136]:
i = Arr.T
i

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [137]:
i.shape

(3, 4)

In [151]:
k = Arr.dot(i)
k

array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266],
       [ 68, 167, 266, 365]])

In [152]:
np.max(k)

np.int64(365)

In [153]:
np.min(k)

np.int64(14)

In [155]:
np.argmax(k)

np.int64(15)

In [156]:
np.argmin(k)

np.int64(0)